int _putchar(char c);
void _islower(int c);
void _isalpha(int c);
void _abs(int n);
void _isupper(int c);
void _isdigit(int c);
void _strlen(char *s);
void _puts(char *s);
void *_strcpy(char *dest, char *src);
void _atoi(char *s);
void *_strcat(char *dest, char *src);
void *_strncat(char *dest, char *src, int n);
void *_strncpy(char *dest, char *src, int n);
void _strcmp(char *s1, char *s2);
void *_memset(char *s, char b, unsigned int n);
void *_memcpy(char *dest, char *src, unsigned int n);
void *_strchr(char *s, char c);
void _strspn(char *s, char *accept);
void *_strpbrk(char *s, char *accept);
void *_strstr(char *haystack, char *needle);